/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGaugeV3Events,
  IGaugeV3EventsInterface,
} from "../../IGaugeV3.sol/IGaugeV3Events";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "minRate",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "maxRate",
        type: "uint16",
      },
    ],
    name: "AddQuotaToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "status",
        type: "bool",
      },
    ],
    name: "SetFrozenEpoch",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "minRate",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "maxRate",
        type: "uint16",
      },
    ],
    name: "SetQuotaTokenParams",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "votes",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "lpSide",
        type: "bool",
      },
    ],
    name: "Unvote",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint16",
        name: "epochNow",
        type: "uint16",
      },
    ],
    name: "UpdateEpoch",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "votes",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "lpSide",
        type: "bool",
      },
    ],
    name: "Vote",
    type: "event",
  },
] as const;

export class IGaugeV3Events__factory {
  static readonly abi = _abi;
  static createInterface(): IGaugeV3EventsInterface {
    return new utils.Interface(_abi) as IGaugeV3EventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGaugeV3Events {
    return new Contract(address, _abi, signerOrProvider) as IGaugeV3Events;
  }
}
