[profile.default]
libs = ['lib']
out = 'forge-out'
solc_version = '0.8.17'
evm_version = 'shanghai'
src = 'contracts'
optimizer_runs = 12000

# See more config options https://github.com/gakonst/foundry/tree/master/config
block_number = 120000 
block_timestamp = 16400000 
gas_limit = 9223372036854775807 # the gas limit in tests
block_base_fee_per_gas = 100
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
max_test_rejects = 200000

[invariant]
fail_on_revert = true
runs = 200
depth = 10
