[profile.default]
libs = ['lib']
out = 'forge-out'
remappings = [
  'ds-test/=lib/ds-test/src/',
  '@ensdomains/=node_modules/@ensdomains/',
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@chainlink/=node_modules/@chainlink/',
  'hardhat/=node_modules/hardhat/',
  '@gearbox-protocol=node_modules/@gearbox-protocol/'
]
solc_version = '0.8.17'
src = 'contracts'
optimizer_runs = 20000

# See more config options https://github.com/gakonst/foundry/tree/master/config
block_number = 120000 
block_timestamp = 16400000 
gas_limit = 9223372036854775807 # the gas limit in tests
block_base_fee_per_gas = 100
fs_permissions = [{ access = "read-write", path = "./"}]
