/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IControllerTimelockV3__factory } from "./IControllerTimelockV3__factory";
export { IControllerTimelockV3Events__factory } from "./IControllerTimelockV3Events__factory";
