/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICreditAccountBase } from "./ICreditAccountBase";
export type { ICreditAccountV3 } from "./ICreditAccountV3";
