/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolQuotaKeeperV3Events,
  IPoolQuotaKeeperV3EventsInterface,
} from "../../IPoolQuotaKeeperV3.sol/IPoolQuotaKeeperV3Events";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creditManager",
        type: "address",
      },
    ],
    name: "AddCreditManager",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "AddQuotaToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newGauge",
        type: "address",
      },
    ],
    name: "SetGauge",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "fee",
        type: "uint16",
      },
    ],
    name: "SetQuotaIncreaseFee",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "limit",
        type: "uint96",
      },
    ],
    name: "SetTokenLimit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creditAccount",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "int96",
        name: "quotaChange",
        type: "int96",
      },
    ],
    name: "UpdateQuota",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "rate",
        type: "uint16",
      },
    ],
    name: "UpdateTokenQuotaRate",
    type: "event",
  },
] as const;

export class IPoolQuotaKeeperV3Events__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolQuotaKeeperV3EventsInterface {
    return new utils.Interface(_abi) as IPoolQuotaKeeperV3EventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolQuotaKeeperV3Events {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPoolQuotaKeeperV3Events;
  }
}
